name: curl下载保存到库

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '要下载的文件的 URL'
        required: true
        default: 'https://example.com/file.zip'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取存储库
      uses: actions/checkout@v2

    - name: 下载文件
      run: |
        echo "Downloading file from URL: ${{ github.event.inputs.download_url }}"
        curl -L -O "${{ github.event.inputs.download_url }}"

    - name: 配置Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: 将文件提交到存储库
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Add downloaded file"
        git push
